# Generated by go2rpm 1.16.0.post0
%bcond check 1

# https://github.com/containers/podman-bootc
%global goipath         github.com/containers/podman-bootc
Version:                0.1.2

%gometa -L -f

%global common_description %{expand:
A scriptable CLI that offers an efficient and ergonomic "edit-compile-debug"
cycle for bootable containers.}

Name:           podman-bootc
Release:        %autorelease
Summary:        Streamlining podman + bootc interactions

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT AND MPL-2.0 AND Unlicense
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools
# make needed for man generation but not available in release
# BuildRequires:  make
BuildRequires:  gcc
BuildRequires:  libvirt-devel
BuildRequires:  go-md2man

Requires:       podman-machine
Requires:       xorriso
Requires:       podman
Requires:       qemu
Requires:       libvirt

%description %{common_description}

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}
%autopatch -p1

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
# explicitly turn on module support for gotest and gobuild
%global gomodulesmode GO111MODULE=on

# define global for use in gobuild and gotest
%global buildtags exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp remote
export GO_BUILDTAGS="%{buildtags}"

%gobuild -o %{gobuilddir}/bin/podman-bootc %{goipath}

# docs directory not included in current source tar file
# build man files
# %%make_build docs

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
# docs directory not included in current source tar file
# install -m 0755 -vd                     %%{buildroot}%%{_mandir}/man1
# install -m 0755 -vp docs/*.1            %%{buildroot}%%{_mandir}/man1/

%check
%go_vendor_license_check -c %{S:2}

%if %{with check}

# redefine gotestflags to include needed buildtags
%define gotestflags %{gocompilerflags} '-tags=%{buildtags}'

# skip ./pkg/vms - cannot run vm tests in build
# skip ./test - end-to-end integration tests that cannot run in build
%gotest $(go list ./... | awk '!/(vm|test)/ {print $1}')
%endif

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc README.md
%{_bindir}/podman-bootc
# docs directory not included in current source tar file
# %%{_mandir}/man1/*.1*

%changelog
%autochangelog
